
theme: jekyll-theme-slate

defaults:
    -
     scope:
         path: ""
     values:
         author: "Anthony Granger"
         layout: post
         lang: en
         base-url: "/"
    -
     scope:
         path: ru
     values:
         lang: ru
         base-url: "/ru/"

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate